// internationalization/dicts.js

// AVAILABLE LANGUAGES: en, es, pt, ja, zh, hi, ar, de, fr, ru, it, nl, pl, tr

export const DICTS = {
    en: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "Minimal routine list. Create and manage training plans locally.",

        "common.back": "Back",
        "common.close": "Close",
        "common.cancel": "Cancel",
        "common.create": "Create",
        "common.delete": "Delete",
        "common.clearAll": "Clear all",

        "confirm.clearAll": "This will delete ALL routines from this device. Continue?",

        "routines.title": "Your routines",
        "routines.new": "+ New routine",
        "routines.empty.prefix": "No routines yet. Click",
        "routines.empty.cta": "+ New routine",
        "routines.empty.suffix": "to create your first one.",

        "routineNew.title": "Create routine",
        "routineNew.nameLabel": "Name",
        "routineNew.namePlaceholder": "e.g., Push Day A",
        "routineNew.descriptionLabel": "Description (optional)",
        "routineNew.descriptionPlaceholder": "Quick notes: goals, intensity, focus...",
        "routineNew.note": "Saved on this device (localStorage). You can add exercises later in the routine screen.",

        "routine.addSeries.title": "Add exercise",
        "routine.addSeries.exerciseLabel": "Exercise",
        "routine.addSeries.exercisePlaceholder": "Type or pick an exercise...",
        "routine.addSeries.exerciseHelp": "Type a new name to create an exercise automatically.",
        "routine.addSeries.seriesDescriptionLabel": "Exercise description (optional)",
        "routine.addSeries.seriesDescriptionPlaceholder": "e.g., Working sets, Warm-up...",
        "routine.addSeries.button": "Add exercise",

        "routine.seriesList.title": "Exercises in this routine",
        "routine.seriesList.empty": "No exercises yet. Add one above.",

        "seriesEditor.seriesDescriptionLabel": "Exercise description",
        "seriesEditor.seriesDescriptionPlaceholder": "e.g., Working sets",
        "seriesEditor.restAfterSeriesLabel": "Rest after exercise (seconds)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "Save exercise",

        "seriesEditor.repGroupsTitle": "Sets",
        "seriesEditor.repGroupsEmpty": "No sets yet. Add one below.",
        "seriesEditor.addRepGroupTitle": "Add set",
        "seriesEditor.addRepGroupButton": "Add set",

        "repGroup.lateralityLabel": "Laterality",
        "repGroup.laterality.bilateral": "Bilateral",
        "repGroup.laterality.unilateral": "Unilateral",
        "repGroup.targetRepsLabel": "Target reps",
        "repGroup.targetRepsPlaceholder": "e.g., 10",
        "repGroup.targetWeightSingleLabel": "Target weight",
        "repGroup.targetWeightSinglePlaceholder": "e.g., 30",
        "repGroup.targetWeightTupleLabel": "Target weight (left / right)",
        "repGroup.targetWeightLeftPlaceholder": "Left",
        "repGroup.targetWeightRightPlaceholder": "Right",
        "repGroup.restAfterLabel": "Rest after set (seconds)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "Open",
        "common.dash": "—",
        "routines.untitled": "Untitled routine",
        "routines.exercisesCount.one": "{count} exercise",
        "routines.exercisesCount.other": "{count} exercises",
        "routines.seriesCount.one": "{count} set",
        "routines.seriesCount.other": "{count} sets",
        "routines.count.one": "{count} routine",
        "routines.count.other": "{count} routines",
        "routines.confirmDelete": "Delete routine \"{name}\"?",
        "routine.confirmDelete": "Delete routine \"{name}\"?",
        "common.edit": "Edit",
        "common.remove": "Remove",
        "routine.seriesList.restAfter": "Rest after: {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "Remove exercise #{index}?",
        "routine.seriesList.missingExercise": "(missing exercise)",
        "seriesEditor.title": "Edit exercise #{index} · {exercise}",
        "seriesEditor.repGroup.title": "Set #{index}",
        "seriesEditor.repGroup.summary": "{laterality} · reps: {reps} · weight: {weight} · rest: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "Remove set #{index}?",

        "common.download": "Download",
        "routines.downloadHelp": "Download this routine in a fixed format you can use to import your routines",
        "routines.upload": "Upload routine",

        "common.save": "Save",
        "routine.edit.nameLabel": "Name",
        "routine.edit.descLabel": "Description",
        "routine.edit.namePlaceholder": "e.g., Push Day A",
        "routine.edit.descPlaceholder": "Quick notes: goals, intensity, focus...",

        "session.title": "Workout session",
        "session.timer.label": "Timer",
        "session.timer.start": "Start",
        "session.timer.pause": "Pause",
        "session.timer.reset": "Reset",
        "session.series.title": "Exercises",
        "session.series.empty": "This routine has no exercises yet.",
        "session.routineNotFound": "Routine not found.",
        "session.exercise.unknown": "Exercise",
        "session.set": "Set",
        "session.sets": "sets",
        "session.rest": "Rest",
        "session.restAfterExercise": "Rest after exercise",
        "session.exercise.set": "set",
        "session.exercise.sets": "sets",
        "session.currentExercise": "Current exercise",
        "session.noSets": "No sets",
        "session.weight": "Weight",
        "session.reps": "Reps",
        "session.exercise": "Exercise",
        "session.currentSet.timer": "Set timer",
        "session.currentSet.done": "Complete set",
        "session.allSets": "All sets",
    },

    es: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "Lista mínima de rutinas. Crea y gestiona planes de entrenamiento localmente.",

        "common.back": "Volver",
        "common.close": "Cerrar",
        "common.cancel": "Cancelar",
        "common.create": "Crear",
        "common.delete": "Eliminar",
        "common.clearAll": "Borrar todo",

        "confirm.clearAll": "Esto eliminará TODAS las rutinas de este dispositivo. ¿Continuar?",

        "routines.title": "Tus rutinas",
        "routines.new": "+ Nueva rutina",
        "routines.empty.prefix": "Aún no hay rutinas. Pulsa",
        "routines.empty.cta": "+ Nueva rutina",
        "routines.empty.suffix": "para crear la primera.",

        "routineNew.title": "Crear rutina",
        "routineNew.nameLabel": "Nombre",
        "routineNew.namePlaceholder": "p. ej., Empuje A",
        "routineNew.descriptionLabel": "Descripción (opcional)",
        "routineNew.descriptionPlaceholder": "Notas rápidas: objetivos, intensidad, enfoque...",
        "routineNew.note": "Se guarda en este dispositivo (localStorage). Puedes añadir ejercicios después en la pantalla de la rutina.",

        "routine.addSeries.title": "Añadir ejercicio",
        "routine.addSeries.exerciseLabel": "Ejercicio",
        "routine.addSeries.exercisePlaceholder": "Escribe o elige un ejercicio...",
        "routine.addSeries.exerciseHelp": "Escribe un nombre nuevo para crear el ejercicio automáticamente.",
        "routine.addSeries.seriesDescriptionLabel": "Descripción del ejercicio (opcional)",
        "routine.addSeries.seriesDescriptionPlaceholder": "p. ej., Series de trabajo, Calentamiento...",
        "routine.addSeries.button": "Añadir ejercicio",

        "routine.seriesList.title": "Ejercicios de esta rutina",
        "routine.seriesList.empty": "Aún no hay ejercicios. Añade uno arriba.",

        "seriesEditor.seriesDescriptionLabel": "Descripción del ejercicio",
        "seriesEditor.seriesDescriptionPlaceholder": "p. ej., Series de trabajo",
        "seriesEditor.restAfterSeriesLabel": "Descanso tras el ejercicio (segundos)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "Guardar ejercicio",

        "seriesEditor.repGroupsTitle": "Series",
        "seriesEditor.repGroupsEmpty": "Aún no hay series. Añade una abajo.",
        "seriesEditor.addRepGroupTitle": "Añadir serie",
        "seriesEditor.addRepGroupButton": "Añadir serie",

        "repGroup.lateralityLabel": "Lateralidad",
        "repGroup.laterality.bilateral": "Bilateral",
        "repGroup.laterality.unilateral": "Unilateral",
        "repGroup.targetRepsLabel": "Repeticiones objetivo",
        "repGroup.targetRepsPlaceholder": "p. ej., 10",
        "repGroup.targetWeightSingleLabel": "Peso objetivo",
        "repGroup.targetWeightSinglePlaceholder": "p. ej., 30",
        "repGroup.targetWeightTupleLabel": "Peso objetivo (izquierda / derecha)",
        "repGroup.targetWeightLeftPlaceholder": "Izquierda",
        "repGroup.targetWeightRightPlaceholder": "Derecha",
        "repGroup.restAfterLabel": "Descanso tras la serie (segundos)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "Abrir",
        "common.dash": "—",
        "routines.untitled": "Rutina sin título",
        "routines.exercisesCount.one": "{count} ejercicio",
        "routines.exercisesCount.other": "{count} ejercicios",
        "routines.seriesCount.one": "{count} serie",
        "routines.seriesCount.other": "{count} series",
        "routines.count.one": "{count} rutina",
        "routines.count.other": "{count} rutinas",
        "routines.confirmDelete": "¿Eliminar la rutina \"{name}\"?",
        "routine.confirmDelete": "¿Eliminar la rutina \"{name}\"?",
        "common.edit": "Editar",
        "common.remove": "Quitar",
        "routine.seriesList.restAfter": "Descanso después: {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "¿Quitar el ejercicio #{index}?",
        "routine.seriesList.missingExercise": "(ejercicio no encontrado)",
        "seriesEditor.title": "Editar ejercicio #{index} · {exercise}",
        "seriesEditor.repGroup.title": "Serie #{index}",
        "seriesEditor.repGroup.summary": "{laterality} · repeticiones: {reps} · peso: {weight} · descanso: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "¿Quitar la serie #{index}?",

        "common.download": "Descargar",
        "routines.downloadHelp": "Descarga esta rutina en un formato fijo que puedes usar para importar tus rutinas",
        "routines.upload": "Subir rutina",

        "common.save": "Guardar",
        "routine.edit.nameLabel": "Nombre",
        "routine.edit.descLabel": "Descripción",
        "routine.edit.namePlaceholder": "p. ej., Empuje Día A",
        "routine.edit.descPlaceholder": "Notas rápidas: objetivos, intensidad, enfoque...",

        "session.title": "Sesión de entrenamiento",
        "session.timer.label": "Temporizador",
        "session.timer.start": "Iniciar",
        "session.timer.pause": "Pausar",
        "session.timer.reset": "Reiniciar",
        "session.series.title": "Ejercicios",
        "session.series.empty": "Esta rutina no tiene ejercicios todavía.",
        "session.routineNotFound": "Rutina no encontrada.",
        "session.exercise.unknown": "Ejercicio",
        "session.set": "Serie",
        "session.sets": "series",
        "session.rest": "Descanso",
        "session.restAfterExercise": "Descanso tras el ejercicio",
        "session.exercise.set": "serie",
        "session.exercise.sets": "series",
        "session.currentExercise": "Ejercicio actual",
        "session.noSets": "Sin series",
        "session.weight": "Peso",
        "session.reps": "Repeticiones",
        "session.exercise": "Ejercicio",
        "session.currentSet.timer": "Temporizador de la serie",
        "session.currentSet.done": "Completar serie",
        "session.allSets": "Todas las series",
    },

    pt: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "Lista mínima de rotinas. Crie e gerencie planos de treino localmente.",

        "common.back": "Voltar",
        "common.close": "Fechar",
        "common.cancel": "Cancelar",
        "common.create": "Criar",
        "common.delete": "Excluir",
        "common.clearAll": "Apagar tudo",

        "confirm.clearAll": "Isto apagará TODAS as rotinas deste dispositivo. Continuar?",

        "routines.title": "Suas rotinas",
        "routines.new": "+ Nova rotina",
        "routines.empty.prefix": "Ainda não há rotinas. Toque em",
        "routines.empty.cta": "+ Nova rotina",
        "routines.empty.suffix": "para criar a primeira.",

        "routineNew.title": "Criar rotina",
        "routineNew.nameLabel": "Nome",
        "routineNew.namePlaceholder": "ex.: Push Day A",
        "routineNew.descriptionLabel": "Descrição (opcional)",
        "routineNew.descriptionPlaceholder": "Notas rápidas: objetivos, intensidade, foco...",
        "routineNew.note": "Salvo neste dispositivo (localStorage). Você pode adicionar exercícios depois na tela da rotina.",

        "routine.addSeries.title": "Adicionar exercício",
        "routine.addSeries.exerciseLabel": "Exercício",
        "routine.addSeries.exercisePlaceholder": "Digite ou escolha um exercício...",
        "routine.addSeries.exerciseHelp": "Digite um nome novo para criar o exercício automaticamente.",
        "routine.addSeries.seriesDescriptionLabel": "Descrição do exercício (opcional)",
        "routine.addSeries.seriesDescriptionPlaceholder": "ex.: Séries de trabalho, Aquecimento...",
        "routine.addSeries.button": "Adicionar exercício",

        "routine.seriesList.title": "Exercícios nesta rotina",
        "routine.seriesList.empty": "Ainda não há exercícios. Adicione um acima.",

        "seriesEditor.seriesDescriptionLabel": "Descrição do exercício",
        "seriesEditor.seriesDescriptionPlaceholder": "ex.: Séries de trabalho",
        "seriesEditor.restAfterSeriesLabel": "Descanso após o exercício (segundos)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "Salvar exercício",

        "seriesEditor.repGroupsTitle": "Séries",
        "seriesEditor.repGroupsEmpty": "Ainda não há séries. Adicione uma abaixo.",
        "seriesEditor.addRepGroupTitle": "Adicionar série",
        "seriesEditor.addRepGroupButton": "Adicionar série",

        "repGroup.lateralityLabel": "Lateralidade",
        "repGroup.laterality.bilateral": "Bilateral",
        "repGroup.laterality.unilateral": "Unilateral",
        "repGroup.targetRepsLabel": "Repetições alvo",
        "repGroup.targetRepsPlaceholder": "ex.: 10",
        "repGroup.targetWeightSingleLabel": "Peso alvo",
        "repGroup.targetWeightSinglePlaceholder": "ex.: 30",
        "repGroup.targetWeightTupleLabel": "Peso alvo (esquerda / direita)",
        "repGroup.targetWeightLeftPlaceholder": "Esquerda",
        "repGroup.targetWeightRightPlaceholder": "Direita",
        "repGroup.restAfterLabel": "Descanso após a série (segundos)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "Abrir",
        "common.dash": "—",
        "routines.untitled": "Rotina sem título",
        "routines.exercisesCount.one": "{count} exercício",
        "routines.exercisesCount.other": "{count} exercícios",
        "routines.seriesCount.one": "{count} série",
        "routines.seriesCount.other": "{count} séries",
        "routines.count.one": "{count} rotina",
        "routines.count.other": "{count} rotinas",
        "routines.confirmDelete": "Excluir rotina \"{name}\"?",
        "routine.confirmDelete": "Excluir rotina \"{name}\"?",
        "common.edit": "Editar",
        "common.remove": "Remover",
        "routine.seriesList.restAfter": "Descanso após: {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "Remover exercício #{index}?",
        "routine.seriesList.missingExercise": "(exercício não encontrado)",
        "seriesEditor.title": "Editar exercício #{index} · {exercise}",
        "seriesEditor.repGroup.title": "Série #{index}",
        "seriesEditor.repGroup.summary": "{laterality} · repetições: {reps} · peso: {weight} · descanso: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "Remover série #{index}?",

        "common.download": "Baixar",
        "routines.downloadHelp": "Baixe esta rotina em um formato fixo que você pode usar para importar suas rotinas",
        "routines.upload": "Enviar rotina",

        "common.save": "Salvar",
        "routine.edit.nameLabel": "Nome",
        "routine.edit.descLabel": "Descrição",
        "routine.edit.namePlaceholder": "ex.: Dia de Empurrar A",
        "routine.edit.descPlaceholder": "Notas rápidas: objetivos, intensidade, foco...",

        "session.title": "Sessão de treino",
        "session.timer.label": "Temporizador",
        "session.timer.start": "Iniciar",
        "session.timer.pause": "Pausar",
        "session.timer.reset": "Reiniciar",
        "session.series.title": "Exercícios",
        "session.series.empty": "Esta rotina ainda não tem exercícios.",
        "session.routineNotFound": "Rotina não encontrada.",
        "session.exercise.unknown": "Exercício",
        "session.set": "Série",
        "session.sets": "séries",
        "session.rest": "Descanso",
        "session.restAfterExercise": "Descanso após o exercício",
        "session.exercise.set": "série",
        "session.exercise.sets": "séries",
        "session.currentExercise": "Exercício atual",
        "session.noSets": "Sem séries",
        "session.weight": "Peso",
        "session.reps": "Repetições",
        "session.exercise": "Exercício",
        "session.currentSet.timer": "Temporizador da série",
        "session.currentSet.done": "Completar série",
        "session.allSets": "Todas as séries",
    },

    ja: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "最小限のルーティン一覧。端末内でトレーニング計画を作成・管理できます。",

        "common.back": "戻る",
        "common.close": "閉じる",
        "common.cancel": "キャンセル",
        "common.create": "作成",
        "common.delete": "削除",
        "common.clearAll": "すべて削除",

        "confirm.clearAll": "この端末のルーティンをすべて削除します。続行しますか？",

        "routines.title": "あなたのルーティン",
        "routines.new": "+ 新しいルーティン",
        "routines.empty.prefix": "ルーティンがありません。",
        "routines.empty.cta": "+ 新しいルーティン",
        "routines.empty.suffix": "をクリックして最初のルーティンを作成しましょう。",

        "routineNew.title": "ルーティンを作成",
        "routineNew.nameLabel": "名前",
        "routineNew.namePlaceholder": "例：プッシュA",
        "routineNew.descriptionLabel": "説明（任意）",
        "routineNew.descriptionPlaceholder": "メモ：目標、強度、重点など...",
        "routineNew.note": "この端末に保存されます（localStorage）。後からルーティン画面でエクササイズを追加できます。",

        "routine.addSeries.title": "エクササイズを追加",
        "routine.addSeries.exerciseLabel": "エクササイズ",
        "routine.addSeries.exercisePlaceholder": "エクササイズを入力または選択...",
        "routine.addSeries.exerciseHelp": "新しい名前を入力すると自動的にエクササイズを作成します。",
        "routine.addSeries.seriesDescriptionLabel": "エクササイズの説明（任意）",
        "routine.addSeries.seriesDescriptionPlaceholder": "例：メインセット、ウォームアップ...",
        "routine.addSeries.button": "エクササイズを追加",

        "routine.seriesList.title": "このルーティンのエクササイズ",
        "routine.seriesList.empty": "まだエクササイズがありません。上で追加してください。",

        "seriesEditor.seriesDescriptionLabel": "エクササイズの説明",
        "seriesEditor.seriesDescriptionPlaceholder": "例：メインセット",
        "seriesEditor.restAfterSeriesLabel": "エクササイズ後の休憩（秒）",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "エクササイズを保存",

        "seriesEditor.repGroupsTitle": "シリーズ",
        "seriesEditor.repGroupsEmpty": "まだシリーズがありません。下で追加してください。",
        "seriesEditor.addRepGroupTitle": "シリーズを追加",
        "seriesEditor.addRepGroupButton": "シリーズを追加",

        "repGroup.lateralityLabel": "左右",
        "repGroup.laterality.bilateral": "両側",
        "repGroup.laterality.unilateral": "片側",
        "repGroup.targetRepsLabel": "目標回数",
        "repGroup.targetRepsPlaceholder": "例：10",
        "repGroup.targetWeightSingleLabel": "目標重量",
        "repGroup.targetWeightSinglePlaceholder": "例：30",
        "repGroup.targetWeightTupleLabel": "目標重量（左 / 右）",
        "repGroup.targetWeightLeftPlaceholder": "左",
        "repGroup.targetWeightRightPlaceholder": "右",
        "repGroup.restAfterLabel": "シリーズ後の休憩（秒）",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "開く",
        "common.dash": "—",
        "routines.untitled": "無題のルーティン",
        "routines.exercisesCount.one": "{count} エクササイズ",
        "routines.exercisesCount.other": "{count} エクササイズ",
        "routines.seriesCount.one": "{count} シリーズ",
        "routines.seriesCount.other": "{count} シリーズ",
        "routines.count.one": "{count} ルーティン",
        "routines.count.other": "{count} ルーティン",
        "routines.confirmDelete": "ルーティン「{name}」を削除しますか？",
        "routine.confirmDelete": "ルーティン「{name}」を削除しますか？",
        "common.edit": "編集",
        "common.remove": "削除",
        "routine.seriesList.restAfter": "休憩時間: {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "エクササイズ #{index} を削除しますか？",
        "routine.seriesList.missingExercise": "(エクササイズが見つかりません)",
        "seriesEditor.title": "エクササイズ #{index} を編集 · {exercise}",
        "seriesEditor.repGroup.title": "シリーズ #{index}",
        "seriesEditor.repGroup.summary": "{laterality} · 回数: {reps} · 重量: {weight} · 休憩: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "シリーズ #{index} を削除しますか？",

        "common.download": "ダウンロード",
        "routines.downloadHelp": "このルーティンをインポート可能な固定フォーマットでダウンロードします",
        "routines.upload": "ルーティンをアップロード",

        "common.save": "保存",
        "routine.edit.nameLabel": "名前",
        "routine.edit.descLabel": "説明",
        "routine.edit.namePlaceholder": "例：プッシュ Day A",
        "routine.edit.descPlaceholder": "メモ：目標、強度、重点など...",

        "session.title": "トレーニングセッション",
        "session.timer.label": "タイマー",
        "session.timer.start": "開始",
        "session.timer.pause": "一時停止",
        "session.timer.reset": "リセット",
        "session.series.title": "エクササイズ",
        "session.series.empty": "このルーティンにはまだエクササイズがありません。",
        "session.routineNotFound": "ルーティンが見つかりません。",
        "session.exercise.unknown": "エクササイズ",
        "session.set": "セット",
        "session.sets": "セット",
        "session.rest": "休憩",
        "session.restAfterExercise": "エクササイズ後の休憩",
        "session.exercise.set": "セット",
        "session.exercise.sets": "セット",
        "session.currentExercise": "現在の種目",
        "session.noSets": "セットなし",
        "session.weight": "重量",
        "session.reps": "回数",
        "session.exercise": "エクササイズ",
        "session.currentSet.timer": "セットタイマー",
        "session.currentSet.done": "セット完了",
        "session.allSets": "すべてのセット",
    },

    zh: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "极简训练计划列表。在本设备本地创建并管理训练计划。",

        "common.back": "返回",
        "common.close": "关闭",
        "common.cancel": "取消",
        "common.create": "创建",
        "common.delete": "删除",
        "common.clearAll": "全部清除",

        "confirm.clearAll": "这将删除此设备上的所有训练计划。是否继续？",

        "routines.title": "你的训练计划",
        "routines.new": "+ 新建训练计划",
        "routines.empty.prefix": "还没有训练计划。点击",
        "routines.empty.cta": "+ 新建训练计划",
        "routines.empty.suffix": "创建第一个。",

        "routineNew.title": "创建训练计划",
        "routineNew.nameLabel": "名称",
        "routineNew.namePlaceholder": "例如：推 A",
        "routineNew.descriptionLabel": "描述（可选）",
        "routineNew.descriptionPlaceholder": "快速备注：目标、强度、重点...",
        "routineNew.note": "保存在此设备（localStorage）。你可以稍后在训练计划页面添加动作。",

        "routine.addSeries.title": "添加动作",
        "routine.addSeries.exerciseLabel": "动作",
        "routine.addSeries.exercisePlaceholder": "输入或选择一个动作...",
        "routine.addSeries.exerciseHelp": "输入新名称将自动创建动作。",
        "routine.addSeries.seriesDescriptionLabel": "动作描述（可选）",
        "routine.addSeries.seriesDescriptionPlaceholder": "例如：正式组、热身...",
        "routine.addSeries.button": "添加动作",

        "routine.seriesList.title": "本训练计划的动作",
        "routine.seriesList.empty": "还没有动作。请在上方添加。",

        "seriesEditor.seriesDescriptionLabel": "动作描述",
        "seriesEditor.seriesDescriptionPlaceholder": "例如：正式组",
        "seriesEditor.restAfterSeriesLabel": "动作后休息（秒）",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "保存动作",

        "seriesEditor.repGroupsTitle": "组",
        "seriesEditor.repGroupsEmpty": "还没有组。请在下方添加。",
        "seriesEditor.addRepGroupTitle": "添加组",
        "seriesEditor.addRepGroupButton": "添加组",

        "repGroup.lateralityLabel": "左右",
        "repGroup.laterality.bilateral": "双侧",
        "repGroup.laterality.unilateral": "单侧",
        "repGroup.targetRepsLabel": "目标次数",
        "repGroup.targetRepsPlaceholder": "例如：10",
        "repGroup.targetWeightSingleLabel": "目标重量",
        "repGroup.targetWeightSinglePlaceholder": "例如：30",
        "repGroup.targetWeightTupleLabel": "目标重量（左 / 右）",
        "repGroup.targetWeightLeftPlaceholder": "左",
        "repGroup.targetWeightRightPlaceholder": "右",
        "repGroup.restAfterLabel": "组后休息（秒）",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "打开",
        "common.dash": "—",
        "routines.untitled": "未命名训练计划",
        "routines.exercisesCount.one": "{count} 个动作",
        "routines.exercisesCount.other": "{count} 个动作",
        "routines.seriesCount.one": "{count} 组",
        "routines.seriesCount.other": "{count} 组",
        "routines.count.one": "{count} 个训练计划",
        "routines.count.other": "{count} 个训练计划",
        "routines.confirmDelete": "删除训练计划「{name}」？",
        "routine.confirmDelete": "删除训练计划「{name}」？",
        "common.edit": "编辑",
        "common.remove": "移除",
        "routine.seriesList.restAfter": "休息时间: {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "移除第 #{index} 个动作？",
        "routine.seriesList.missingExercise": "(找不到动作)",
        "seriesEditor.title": "编辑第 #{index} 个动作 · {exercise}",
        "seriesEditor.repGroup.title": "组 #{index}",
        "seriesEditor.repGroup.summary": "{laterality} · 次数: {reps} · 重量: {weight} · 休息: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "移除组 #{index}？",

        "common.download": "下载",
        "routines.downloadHelp": "以固定格式下载此训练计划，你可以使用该格式导入你的训练计划",
        "routines.upload": "上传训练计划",

        "common.save": "保存",
        "routine.edit.nameLabel": "名称",
        "routine.edit.descLabel": "描述",
        "routine.edit.namePlaceholder": "例如：推日 A",
        "routine.edit.descPlaceholder": "简要记录：目标、强度、重点...",

        "session.title": "训练会话",
        "session.timer.label": "计时器",
        "session.timer.start": "开始",
        "session.timer.pause": "暂停",
        "session.timer.reset": "重置",
        "session.series.title": "动作",
        "session.series.empty": "该训练计划尚无练习。",
        "session.routineNotFound": "未找到训练计划。",
        "session.exercise.unknown": "练习",
        "session.set": "组",
        "session.sets": "组",
        "session.rest": "休息",
        "session.restAfterExercise": "动作后休息",
        "session.exercise.set": "组",
        "session.exercise.sets": "组",
        "session.currentExercise": "当前动作",
        "session.noSets": "暂无组数",
        "session.weight": "重量",
        "session.reps": "次数",
        "session.exercise": "动作",
        "session.currentSet.timer": "组计时器",
        "session.currentSet.done": "完成组",
        "session.allSets": "所有组",
    },

    ar: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "قائمة روتينات بسيطة. أنشئ وادِر خطط التدريب محليًا.",

        "common.back": "رجوع",
        "common.close": "إغلاق",
        "common.cancel": "إلغاء",
        "common.create": "إنشاء",
        "common.delete": "حذف",
        "common.clearAll": "مسح الكل",

        "confirm.clearAll": "سيؤدي هذا إلى حذف جميع الروتينات من هذا الجهاز. هل تريد المتابعة؟",

        "routines.title": "روتيناتك",
        "routines.new": "+ روتين جديد",
        "routines.empty.prefix": "لا توجد روتينات بعد. اضغط",
        "routines.empty.cta": "+ روتين جديد",
        "routines.empty.suffix": "لإنشاء أول روتين.",

        "routineNew.title": "إنشاء روتين",
        "routineNew.nameLabel": "الاسم",
        "routineNew.namePlaceholder": "مثال: Push Day A",
        "routineNew.descriptionLabel": "الوصف (اختياري)",
        "routineNew.descriptionPlaceholder": "ملاحظات سريعة: الأهداف، الشدة، التركيز...",
        "routineNew.note": "محفوظ على هذا الجهاز (localStorage). يمكنك إضافة التمارين لاحقًا في شاشة الروتين.",

        "routine.addSeries.title": "إضافة تمرين",
        "routine.addSeries.exerciseLabel": "التمرين",
        "routine.addSeries.exercisePlaceholder": "اكتب أو اختر تمرينًا...",
        "routine.addSeries.exerciseHelp": "اكتب اسمًا جديدًا لإنشاء تمرين تلقائيًا.",
        "routine.addSeries.seriesDescriptionLabel": "وصف التمرين (اختياري)",
        "routine.addSeries.seriesDescriptionPlaceholder": "مثال: مجموعات العمل، الإحماء...",
        "routine.addSeries.button": "إضافة تمرين",

        "routine.seriesList.title": "التمارين في هذا الروتين",
        "routine.seriesList.empty": "لا توجد تمارين بعد. أضف واحدة بالأعلى.",

        "seriesEditor.seriesDescriptionLabel": "وصف التمرين",
        "seriesEditor.seriesDescriptionPlaceholder": "مثال: مجموعات العمل",
        "seriesEditor.restAfterSeriesLabel": "الراحة بعد التمرين (ثوانٍ)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "حفظ التمرين",

        "seriesEditor.repGroupsTitle": "السلاسل",
        "seriesEditor.repGroupsEmpty": "لا توجد سلاسل بعد. أضف واحدة بالأسفل.",
        "seriesEditor.addRepGroupTitle": "إضافة سلسلة",
        "seriesEditor.addRepGroupButton": "إضافة سلسلة",

        "repGroup.lateralityLabel": "الجانبية",
        "repGroup.laterality.bilateral": "ثنائي",
        "repGroup.laterality.unilateral": "أحادي",
        "repGroup.targetRepsLabel": "التكرارات المستهدفة",
        "repGroup.targetRepsPlaceholder": "مثال: 10",
        "repGroup.targetWeightSingleLabel": "الوزن المستهدف",
        "repGroup.targetWeightSinglePlaceholder": "مثال: 30",
        "repGroup.targetWeightTupleLabel": "الوزن المستهدف (يسار / يمين)",
        "repGroup.targetWeightLeftPlaceholder": "يسار",
        "repGroup.targetWeightRightPlaceholder": "يمين",
        "repGroup.restAfterLabel": "الراحة بعد السلسلة (ثوانٍ)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "فتح",
        "common.dash": "—",
        "routines.untitled": "روتين بدون عنوان",
        "routines.exercisesCount.one": "{count} تمرين",
        "routines.exercisesCount.other": "{count} تمارين",
        "routines.seriesCount.one": "{count} سلسلة",
        "routines.seriesCount.other": "{count} سلاسل",
        "routines.count.one": "{count} روتين",
        "routines.count.other": "{count} روتينات",
        "routines.confirmDelete": "هل تريد حذف الروتين \"{name}\"؟",
        "routine.confirmDelete": "هل تريد حذف الروتين \"{name}\"؟",
        "common.edit": "تعديل",
        "common.remove": "إزالة",
        "routine.seriesList.restAfter": "وقت الراحة: {seconds}ث",
        "routine.seriesList.confirmRemoveSeries": "هل تريد إزالة التمرين #{index}؟",
        "routine.seriesList.missingExercise": "(التمرين مفقود)",
        "seriesEditor.title": "تعديل التمرين #{index} · {exercise}",
        "seriesEditor.repGroup.title": "سلسلة #{index}",
        "seriesEditor.repGroup.summary": "{laterality} · التكرارات: {reps} · الوزن: {weight} · الراحة: {restSeconds}ث",
        "seriesEditor.repGroup.confirmRemove": "هل تريد إزالة السلسلة #{index}؟",

        "common.download": "تنزيل",
        "routines.downloadHelp": "قم بتنزيل هذا الروتين بتنسيق ثابت يمكنك استخدامه لاستيراد روتيناتك",
        "routines.upload": "رفع روتين",

        "common.save": "حفظ",
        "routine.edit.nameLabel": "الاسم",
        "routine.edit.descLabel": "الوصف",
        "routine.edit.namePlaceholder": "مثال: يوم الدفع A",
        "routine.edit.descPlaceholder": "ملاحظات سريعة: الأهداف، الشدة، التركيز...",

        "session.title": "جلسة تمرين",
        "session.timer.label": "المؤقت",
        "session.timer.start": "ابدأ",
        "session.timer.pause": "إيقاف مؤقت",
        "session.timer.reset": "إعادة ضبط",
        "session.series.title": "التمارين",
        "session.series.empty": "لا تحتوي هذه الخطة على تمارين بعد.",
        "session.routineNotFound": "لم يتم العثور على الخطة.",
        "session.exercise.unknown": "تمرين",
        "session.set": "مجموعة",
        "session.sets": "مجموعات",
        "session.rest": "راحة",
        "session.restAfterExercise": "راحة بعد التمرين",
        "session.exercise.set": "مجموعة",
        "session.exercise.sets": "مجموعات",
        "session.currentExercise": "التمرين الحالي",
        "session.noSets": "لا توجد مجموعات",
        "session.weight": "الوزن",
        "session.reps": "التكرارات",
        "session.exercise": "تمرين",
        "session.currentSet.timer": "مؤقت المجموعة",
        "session.currentSet.done": "إكمال المجموعة",
        "session.allSets": "جميع المجموعات",
    },

    hi: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "सरल रूटीन सूची। स्थानीय रूप से ट्रेनिंग प्लान बनाएं और मैनेज करें।",

        "common.back": "वापस",
        "common.close": "बंद करें",
        "common.cancel": "रद्द करें",
        "common.create": "बनाएं",
        "common.delete": "हटाएं",
        "common.clearAll": "सब साफ़ करें",

        "confirm.clearAll": "यह इस डिवाइस से सभी रूटीन हटा देगा। जारी रखें?",

        "routines.title": "आपके रूटीन",
        "routines.new": "+ नया रूटीन",
        "routines.empty.prefix": "अभी कोई रूटीन नहीं है।",
        "routines.empty.cta": "+ नया रूटीन",
        "routines.empty.suffix": "पर क्लिक करके पहला रूटीन बनाएं।",

        "routineNew.title": "रूटीन बनाएं",
        "routineNew.nameLabel": "नाम",
        "routineNew.namePlaceholder": "जैसे: Push Day A",
        "routineNew.descriptionLabel": "विवरण (वैकल्पिक)",
        "routineNew.descriptionPlaceholder": "त्वरित नोट्स: लक्ष्य, तीव्रता, फोकस...",
        "routineNew.note": "इस डिवाइस पर सहेजा गया (localStorage)। आप बाद में रूटीन स्क्रीन में एक्सरसाइज़ जोड़ सकते हैं।",

        "routine.addSeries.title": "एक्सरसाइज़ जोड़ें",
        "routine.addSeries.exerciseLabel": "एक्सरसाइज़",
        "routine.addSeries.exercisePlaceholder": "टाइप करें या एक्सरसाइज़ चुनें...",
        "routine.addSeries.exerciseHelp": "नया नाम टाइप करने पर एक्सरसाइज़ अपने आप बन जाएगी।",
        "routine.addSeries.seriesDescriptionLabel": "एक्सरसाइज़ विवरण (वैकल्पिक)",
        "routine.addSeries.seriesDescriptionPlaceholder": "जैसे: वर्किंग सेट्स, वॉर्म-अप...",
        "routine.addSeries.button": "एक्सरसाइज़ जोड़ें",

        "routine.seriesList.title": "इस रूटीन की एक्सरसाइज़",
        "routine.seriesList.empty": "अभी कोई एक्सरसाइज़ नहीं है। ऊपर जोड़ें।",

        "seriesEditor.seriesDescriptionLabel": "एक्सरसाइज़ विवरण",
        "seriesEditor.seriesDescriptionPlaceholder": "जैसे: वर्किंग सेट्स",
        "seriesEditor.restAfterSeriesLabel": "एक्सरसाइज़ के बाद आराम (सेकंड)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "एक्सरसाइज़ सहेजें",

        "seriesEditor.repGroupsTitle": "सीरीज़",
        "seriesEditor.repGroupsEmpty": "अभी कोई सीरीज़ नहीं है। नीचे जोड़ें।",
        "seriesEditor.addRepGroupTitle": "सीरीज़ जोड़ें",
        "seriesEditor.addRepGroupButton": "सीरीज़ जोड़ें",

        "repGroup.lateralityLabel": "लेटरैलिटी",
        "repGroup.laterality.bilateral": "बाइलेटरल",
        "repGroup.laterality.unilateral": "यूनिलेटरल",
        "repGroup.targetRepsLabel": "लक्ष्य रेप्स",
        "repGroup.targetRepsPlaceholder": "जैसे: 10",
        "repGroup.targetWeightSingleLabel": "लक्ष्य वजन",
        "repGroup.targetWeightSinglePlaceholder": "जैसे: 30",
        "repGroup.targetWeightTupleLabel": "लक्ष्य वजन (बायाँ / दायाँ)",
        "repGroup.targetWeightLeftPlaceholder": "बायाँ",
        "repGroup.targetWeightRightPlaceholder": "दायाँ",
        "repGroup.restAfterLabel": "सीरीज़ के बाद आराम (सेकंड)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "खोलें",
        "common.dash": "—",
        "routines.untitled": "शीर्षक रहित रूटीन",
        "routines.exercisesCount.one": "{count} एक्सरसाइज़",
        "routines.exercisesCount.other": "{count} एक्सरसाइज़",
        "routines.seriesCount.one": "{count} सीरीज़",
        "routines.seriesCount.other": "{count} सीरीज़",
        "routines.count.one": "{count} रूटीन",
        "routines.count.other": "{count} रूटीन",
        "routines.confirmDelete": "रूटीन \"{name}\" हटाएं?",
        "routine.confirmDelete": "रूटीन \"{name}\" हटाएं?",
        "common.edit": "संपादित करें",
        "common.remove": "हटाएं",
        "routine.seriesList.restAfter": "आराम समय: {seconds}सेकंड",
        "routine.seriesList.confirmRemoveSeries": "एक्सरसाइज़ #{index} हटाएं?",
        "routine.seriesList.missingExercise": "(एक्सरसाइज़ गायब है)",
        "seriesEditor.title": "एक्सरसाइज़ #{index} संपादित करें · {exercise}",
        "seriesEditor.repGroup.title": "सीरीज़ #{index}",
        "seriesEditor.repGroup.summary": "{laterality} · रेप्स: {reps} · वजन: {weight} · आराम: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "सीरीज़ #{index} हटाएं?",

        "common.download": "डाउनलोड करें",
        "routines.downloadHelp": "इस रूटीन को एक स्थिर फॉर्मेट में डाउनलोड करें जिसका उपयोग आप अपनी रूटीन आयात करने के लिए कर सकते हैं",
        "routines.upload": "रूटीन अपलोड करें",

        "common.save": "सहेजें",
        "routine.edit.nameLabel": "नाम",
        "routine.edit.descLabel": "विवरण",
        "routine.edit.namePlaceholder": "जैसे, पुश डे A",
        "routine.edit.descPlaceholder": "त्वरित नोट्स: लक्ष्य, तीव्रता, फोकस...",

        "session.title": "वर्कआउट सत्र",
        "session.timer.label": "टाइमर",
        "session.timer.start": "शुरू करें",
        "session.timer.pause": "रोकें",
        "session.timer.reset": "रीसेट",
        "session.series.title": "एक्सरसाइज़",
        "session.series.empty": "इस रूटीन में अभी कोई अभ्यास नहीं है।",
        "session.routineNotFound": "रूटीन नहीं मिली।",
        "session.exercise.unknown": "अभ्यास",
        "session.set": "सेट",
        "session.sets": "सेट",
        "session.rest": "आराम",
        "session.restAfterExercise": "एक्सरसाइज़ के बाद आराम",
        "session.exercise.set": "सेट",
        "session.exercise.sets": "सेट",
        "session.currentExercise": "वर्तमान व्यायाम",
        "session.noSets": "कोई सेट नहीं",
        "session.weight": "वजन",
        "session.reps": "दोहराव",
        "session.exercise": "एक्सरसाइज़",
        "session.currentSet.timer": "सेट टाइमर",
        "session.currentSet.done": "सेट पूरा करें",
        "session.allSets": "सभी सेट",
    },

    de: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "Minimale Routinenliste. Trainingspläne lokal erstellen und verwalten.",

        "common.back": "Zurück",
        "common.close": "Schließen",
        "common.cancel": "Abbrechen",
        "common.create": "Erstellen",
        "common.delete": "Löschen",
        "common.clearAll": "Alles löschen",

        "confirm.clearAll": "Dies löscht ALLE Routinen von diesem Gerät. Fortfahren?",

        "routines.title": "Deine Routinen",
        "routines.new": "+ Neue Routine",
        "routines.empty.prefix": "Noch keine Routinen. Klicke auf",
        "routines.empty.cta": "+ Neue Routine",
        "routines.empty.suffix": "um deine erste zu erstellen.",

        "routineNew.title": "Routine erstellen",
        "routineNew.nameLabel": "Name",
        "routineNew.namePlaceholder": "z. B. Push Day A",
        "routineNew.descriptionLabel": "Beschreibung (optional)",
        "routineNew.descriptionPlaceholder": "Kurze Notizen: Ziele, Intensität, Fokus...",
        "routineNew.note": "Auf diesem Gerät gespeichert (localStorage). Du kannst später in der Routinenansicht Übungen hinzufügen.",

        "routine.addSeries.title": "Übung hinzufügen",
        "routine.addSeries.exerciseLabel": "Übung",
        "routine.addSeries.exercisePlaceholder": "Übung eingeben oder auswählen...",
        "routine.addSeries.exerciseHelp": "Gib einen neuen Namen ein, um die Übung automatisch zu erstellen.",
        "routine.addSeries.seriesDescriptionLabel": "Übungsbeschreibung (optional)",
        "routine.addSeries.seriesDescriptionPlaceholder": "z. B. Arbeitssätze, Aufwärmen...",
        "routine.addSeries.button": "Übung hinzufügen",

        "routine.seriesList.title": "Übungen in dieser Routine",
        "routine.seriesList.empty": "Noch keine Übungen. Füge oben eine hinzu.",

        "seriesEditor.seriesDescriptionLabel": "Übungsbeschreibung",
        "seriesEditor.seriesDescriptionPlaceholder": "z. B. Arbeitssätze",
        "seriesEditor.restAfterSeriesLabel": "Pause nach der Übung (Sekunden)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "Übung speichern",

        "seriesEditor.repGroupsTitle": "Sätze",
        "seriesEditor.repGroupsEmpty": "Noch keine Sätze. Füge unten einen hinzu.",
        "seriesEditor.addRepGroupTitle": "Satz hinzufügen",
        "seriesEditor.addRepGroupButton": "Satz hinzufügen",

        "repGroup.lateralityLabel": "Lateralisierung",
        "repGroup.laterality.bilateral": "Beidseitig",
        "repGroup.laterality.unilateral": "Einseitig",
        "repGroup.targetRepsLabel": "Ziel-Wiederholungen",
        "repGroup.targetRepsPlaceholder": "z. B. 10",
        "repGroup.targetWeightSingleLabel": "Zielgewicht",
        "repGroup.targetWeightSinglePlaceholder": "z. B. 30",
        "repGroup.targetWeightTupleLabel": "Zielgewicht (links / rechts)",
        "repGroup.targetWeightLeftPlaceholder": "Links",
        "repGroup.targetWeightRightPlaceholder": "Rechts",
        "repGroup.restAfterLabel": "Pause nach dem Satz (Sekunden)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "Öffnen",
        "common.dash": "—",
        "routines.untitled": "Routine ohne Titel",
        "routines.exercisesCount.one": "{count} Übung",
        "routines.exercisesCount.other": "{count} Übungen",
        "routines.seriesCount.one": "{count} Satz",
        "routines.seriesCount.other": "{count} Sätze",
        "routines.count.one": "{count} Routine",
        "routines.count.other": "{count} Routinen",
        "routines.confirmDelete": "Routine \"{name}\" löschen?",
        "routine.confirmDelete": "Routine \"{name}\" löschen?",
        "common.edit": "Bearbeiten",
        "common.remove": "Entfernen",
        "routine.seriesList.restAfter": "Pause nach: {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "Übung #{index} entfernen?",
        "routine.seriesList.missingExercise": "(Übung nicht gefunden)",
        "seriesEditor.title": "Übung #{index} bearbeiten · {exercise}",
        "seriesEditor.repGroup.title": "Satz #{index}",
        "seriesEditor.repGroup.summary": "{laterality} · Wiederholungen: {reps} · Gewicht: {weight} · Pause: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "Satz #{index} entfernen?",

        "common.download": "Herunterladen",
        "routines.downloadHelp": "Lade diese Routine in einem festen Format herunter, das du zum Importieren deiner Routinen verwenden kannst",
        "routines.upload": "Routine hochladen",

        "common.save": "Speichern",
        "routine.edit.nameLabel": "Name",
        "routine.edit.descLabel": "Beschreibung",
        "routine.edit.namePlaceholder": "z. B. Push Day A",
        "routine.edit.descPlaceholder": "Kurze Notizen: Ziele, Intensität, Fokus...",

        "session.title": "Trainingseinheit",
        "session.timer.label": "Timer",
        "session.timer.start": "Start",
        "session.timer.pause": "Pause",
        "session.timer.reset": "Zurücksetzen",
        "session.series.title": "Übungen",
        "session.series.empty": "Diese Routine enthält noch keine Übungen.",
        "session.routineNotFound": "Routine nicht gefunden.",
        "session.exercise.unknown": "Übung",
        "session.set": "Satz",
        "session.sets": "Sätze",
        "session.rest": "Pause",
        "session.restAfterExercise": "Pause nach der Übung",
        "session.exercise.set": "Satz",
        "session.exercise.sets": "Sätze",
        "session.currentExercise": "Aktuelle Übung",
        "session.noSets": "Keine Sätze",
        "session.weight": "Gewicht",
        "session.reps": "Wiederholungen",
        "session.exercise": "Übung",
        "session.currentSet.timer": "Satz-Timer",
        "session.currentSet.done": "Satz abgeschlossen",
        "session.allSets": "Alle Sätze",
    },

    fr: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "Liste de routines minimale. Créez et gérez vos plans d'entraînement en local.",

        "common.back": "Retour",
        "common.close": "Fermer",
        "common.cancel": "Annuler",
        "common.create": "Créer",
        "common.delete": "Supprimer",
        "common.clearAll": "Tout effacer",

        "confirm.clearAll": "Cela supprimera TOUTES les routines de cet appareil. Continuer ?",

        "routines.title": "Vos routines",
        "routines.new": "+ Nouvelle routine",
        "routines.empty.prefix": "Aucune routine pour l'instant. Cliquez sur",
        "routines.empty.cta": "+ Nouvelle routine",
        "routines.empty.suffix": "pour créer la première.",

        "routineNew.title": "Créer une routine",
        "routineNew.nameLabel": "Nom",
        "routineNew.namePlaceholder": "ex. : Push Day A",
        "routineNew.descriptionLabel": "Description (optionnelle)",
        "routineNew.descriptionPlaceholder": "Notes rapides : objectifs, intensité, focus...",
        "routineNew.note": "Enregistré sur cet appareil (localStorage). Vous pourrez ajouter des exercices plus tard dans l'écran de la routine.",

        "routine.addSeries.title": "Ajouter un exercice",
        "routine.addSeries.exerciseLabel": "Exercice",
        "routine.addSeries.exercisePlaceholder": "Saisissez ou choisissez un exercice...",
        "routine.addSeries.exerciseHelp": "Saisissez un nouveau nom pour créer l'exercice automatiquement.",
        "routine.addSeries.seriesDescriptionLabel": "Description de l’exercice (optionnelle)",
        "routine.addSeries.seriesDescriptionPlaceholder": "ex. : Séries de travail, Échauffement...",
        "routine.addSeries.button": "Ajouter l’exercice",

        "routine.seriesList.title": "Exercices dans cette routine",
        "routine.seriesList.empty": "Aucun exercice pour l'instant. Ajoutez-en un ci-dessus.",

        "seriesEditor.seriesDescriptionLabel": "Description de l’exercice",
        "seriesEditor.seriesDescriptionPlaceholder": "ex. : Séries de travail",
        "seriesEditor.restAfterSeriesLabel": "Repos après l’exercice (secondes)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "Enregistrer l’exercice",

        "seriesEditor.repGroupsTitle": "Séries",
        "seriesEditor.repGroupsEmpty": "Aucune série pour l'instant. Ajoutez-en une ci-dessous.",
        "seriesEditor.addRepGroupTitle": "Ajouter une série",
        "seriesEditor.addRepGroupButton": "Ajouter une série",

        "repGroup.lateralityLabel": "Latéralité",
        "repGroup.laterality.bilateral": "Bilatéral",
        "repGroup.laterality.unilateral": "Unilatéral",
        "repGroup.targetRepsLabel": "Répétitions cibles",
        "repGroup.targetRepsPlaceholder": "ex. : 10",
        "repGroup.targetWeightSingleLabel": "Charge cible",
        "repGroup.targetWeightSinglePlaceholder": "ex. : 30",
        "repGroup.targetWeightTupleLabel": "Charge cible (gauche / droite)",
        "repGroup.targetWeightLeftPlaceholder": "Gauche",
        "repGroup.targetWeightRightPlaceholder": "Droite",
        "repGroup.restAfterLabel": "Repos après la série (secondes)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "Ouvrir",
        "common.dash": "—",
        "routines.untitled": "Routine sans titre",
        "routines.exercisesCount.one": "{count} exercice",
        "routines.exercisesCount.other": "{count} exercices",
        "routines.seriesCount.one": "{count} série",
        "routines.seriesCount.other": "{count} séries",
        "routines.count.one": "{count} routine",
        "routines.count.other": "{count} routines",
        "routines.confirmDelete": "Supprimer la routine \"{name}\" ?",
        "routine.confirmDelete": "Supprimer la routine \"{name}\" ?",
        "common.edit": "Modifier",
        "common.remove": "Retirer",
        "routine.seriesList.restAfter": "Temps de repos : {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "Retirer l’exercice n°{index} ?",
        "routine.seriesList.missingExercise": "(exercice introuvable)",
        "seriesEditor.title": "Modifier l’exercice n°{index} · {exercise}",
        "seriesEditor.repGroup.title": "Série n°{index}",
        "seriesEditor.repGroup.summary": "{laterality} · répétitions : {reps} · charge : {weight} · repos : {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "Retirer la série n°{index} ?",

        "common.download": "Télécharger",
        "routines.downloadHelp": "Téléchargez cette routine dans un format fixe que vous pouvez utiliser pour importer vos routines",
        "routines.upload": "Téléverser une routine",

        "common.save": "Enregistrer",
        "routine.edit.nameLabel": "Nom",
        "routine.edit.descLabel": "Description",
        "routine.edit.namePlaceholder": "ex. : Push Day A",
        "routine.edit.descPlaceholder": "Notes rapides : objectifs, intensité, focus...",

        "session.title": "Séance d'entraînement",
        "session.timer.label": "Minuteur",
        "session.timer.start": "Démarrer",
        "session.timer.pause": "Pause",
        "session.timer.reset": "Réinitialiser",
        "session.series.title": "Exercices",
        "session.series.empty": "Cette routine ne contient pas encore d'exercices.",
        "session.routineNotFound": "Routine introuvable.",
        "session.exercise.unknown": "Exercice",
        "session.set": "Série",
        "session.sets": "séries",
        "session.rest": "Repos",
        "session.restAfterExercise": "Repos après l’exercice",
        "session.exercise.set": "série",
        "session.exercise.sets": "séries",
        "session.currentExercise": "Exercice en cours",
        "session.noSets": "Aucune série",
        "session.weight": "Poids",
        "session.reps": "Répétitions",
        "session.exercise": "Exercice",
        "session.currentSet.timer": "Minuteur de la série",
        "session.currentSet.done": "Série terminée",
        "session.allSets": "Toutes les séries",
    },

    ru: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "Минимальный список тренировок. Создавайте и управляйте планами локально.",

        "common.back": "Назад",
        "common.close": "Закрыть",
        "common.cancel": "Отмена",
        "common.create": "Создать",
        "common.delete": "Удалить",
        "common.clearAll": "Очистить всё",

        "confirm.clearAll": "Это удалит ВСЕ тренировки с этого устройства. Продолжить?",

        "routines.title": "Ваши тренировки",
        "routines.new": "+ Новая тренировка",
        "routines.empty.prefix": "Пока нет тренировок. Нажмите",
        "routines.empty.cta": "+ Новая тренировка",
        "routines.empty.suffix": "чтобы создать первую.",

        "routineNew.title": "Создать тренировку",
        "routineNew.nameLabel": "Название",
        "routineNew.namePlaceholder": "например: Push Day A",
        "routineNew.descriptionLabel": "Описание (необязательно)",
        "routineNew.descriptionPlaceholder": "Короткие заметки: цели, интенсивность, фокус...",
        "routineNew.note": "Сохраняется на этом устройстве (localStorage). Упражнения можно добавить позже на экране тренировки.",

        "routine.addSeries.title": "Добавить упражнение",
        "routine.addSeries.exerciseLabel": "Упражнение",
        "routine.addSeries.exercisePlaceholder": "Введите или выберите упражнение...",
        "routine.addSeries.exerciseHelp": "Введите новое имя, чтобы автоматически создать упражнение.",
        "routine.addSeries.seriesDescriptionLabel": "Описание упражнения (необязательно)",
        "routine.addSeries.seriesDescriptionPlaceholder": "например: Рабочие подходы, Разминка...",
        "routine.addSeries.button": "Добавить упражнение",

        "routine.seriesList.title": "Упражнения в этой тренировке",
        "routine.seriesList.empty": "Пока нет упражнений. Добавьте выше.",

        "seriesEditor.seriesDescriptionLabel": "Описание упражнения",
        "seriesEditor.seriesDescriptionPlaceholder": "например: Рабочие подходы",
        "seriesEditor.restAfterSeriesLabel": "Отдых после упражнения (сек.)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "Сохранить упражнение",

        "seriesEditor.repGroupsTitle": "Подходы",
        "seriesEditor.repGroupsEmpty": "Пока нет подходов. Добавьте ниже.",
        "seriesEditor.addRepGroupTitle": "Добавить подход",
        "seriesEditor.addRepGroupButton": "Добавить подход",

        "repGroup.lateralityLabel": "Сторона",
        "repGroup.laterality.bilateral": "Двустороннее",
        "repGroup.laterality.unilateral": "Одностороннее",
        "repGroup.targetRepsLabel": "Целевые повторы",
        "repGroup.targetRepsPlaceholder": "например: 10",
        "repGroup.targetWeightSingleLabel": "Целевой вес",
        "repGroup.targetWeightSinglePlaceholder": "например: 30",
        "repGroup.targetWeightTupleLabel": "Целевой вес (лев./прав.)",
        "repGroup.targetWeightLeftPlaceholder": "Лев.",
        "repGroup.targetWeightRightPlaceholder": "Прав.",
        "repGroup.restAfterLabel": "Отдых после подхода (сек.)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "Открыть",
        "common.dash": "—",
        "routines.untitled": "Рутина без названия",
        "routines.exercisesCount.one": "{count} упражнение",
        "routines.exercisesCount.other": "{count} упражнений",
        "routines.seriesCount.one": "{count} подход",
        "routines.seriesCount.other": "{count} подходов",
        "routines.count.one": "{count} тренировка",
        "routines.count.other": "{count} тренировок",
        "routines.confirmDelete": "Удалить тренировку \"{name}\"?",
        "routine.confirmDelete": "Удалить тренировку \"{name}\"?",
        "common.edit": "Редактировать",
        "common.remove": "Удалить",
        "routine.seriesList.restAfter": "Время отдыха: {seconds}с",
        "routine.seriesList.confirmRemoveSeries": "Удалить упражнение №{index}?",
        "routine.seriesList.missingExercise": "(упражнение не найдено)",
        "seriesEditor.title": "Редактировать упражнение №{index} · {exercise}",
        "seriesEditor.repGroup.title": "Подход №{index}",
        "seriesEditor.repGroup.summary": "{laterality} · повторы: {reps} · вес: {weight} · отдых: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "Удалить подход №{index}?",

        "common.download": "Скачать",
        "routines.downloadHelp": "Скачать эту тренировку в фиксированном формате, который вы можете использовать для импорта ваших тренировок",
        "routines.upload": "Загрузить тренировку",

        "common.save": "Сохранить",
        "routine.edit.nameLabel": "Название",
        "routine.edit.descLabel": "Описание",
        "routine.edit.namePlaceholder": "например, Жимовой день A",
        "routine.edit.descPlaceholder": "Короткие заметки: цели, интенсивность, фокус...",

        "session.title": "Тренировочная сессия",
        "session.timer.label": "Таймер",
        "session.timer.start": "Старт",
        "session.timer.pause": "Пауза",
        "session.timer.reset": "Сброс",
        "session.series.title": "Упражнения",
        "session.series.empty": "В этой тренировке пока нет упражнений.",
        "session.routineNotFound": "Тренировка не найдена.",
        "session.exercise.unknown": "Упражнение",
        "session.set": "подход",
        "session.sets": "подходы",
        "session.rest": "Отдых",
        "session.restAfterExercise": "Отдых после упражнения",
        "session.exercise.set": "подход",
        "session.exercise.sets": "подходы",
        "session.currentExercise": "Текущее упражнение",
        "session.noSets": "Нет подходов",
        "session.weight": "Вес",
        "session.reps": "Повторы",
        "session.exercise": "Упражнение",
        "session.currentSet.timer": "Таймер подхода",
        "session.currentSet.done": "Завершить подход",
        "session.allSets": "Все подходы",
    },

    it: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "Elenco routine minimale. Crea e gestisci i piani di allenamento in locale.",

        "common.back": "Indietro",
        "common.close": "Chiudi",
        "common.cancel": "Annulla",
        "common.create": "Crea",
        "common.delete": "Elimina",
        "common.clearAll": "Cancella tutto",

        "confirm.clearAll": "Questo eliminerà TUTTE le routine da questo dispositivo. Continuare?",

        "routines.title": "Le tue routine",
        "routines.new": "+ Nuova routine",
        "routines.empty.prefix": "Nessuna routine ancora. Clicca",
        "routines.empty.cta": "+ Nuova routine",
        "routines.empty.suffix": "per creare la prima.",

        "routineNew.title": "Crea routine",
        "routineNew.nameLabel": "Nome",
        "routineNew.namePlaceholder": "es.: Push Day A",
        "routineNew.descriptionLabel": "Descrizione (opzionale)",
        "routineNew.descriptionPlaceholder": "Note rapide: obiettivi, intensità, focus...",
        "routineNew.note": "Salvato su questo dispositivo (localStorage). Puoi aggiungere esercizi più tardi nella schermata della routine.",

        "routine.addSeries.title": "Aggiungi esercizio",
        "routine.addSeries.exerciseLabel": "Esercizio",
        "routine.addSeries.exercisePlaceholder": "Scrivi o scegli un esercizio...",
        "routine.addSeries.exerciseHelp": "Scrivi un nuovo nome per creare automaticamente l'esercizio.",
        "routine.addSeries.seriesDescriptionLabel": "Descrizione dell’esercizio (opzionale)",
        "routine.addSeries.seriesDescriptionPlaceholder": "es.: Serie di lavoro, Riscaldamento...",
        "routine.addSeries.button": "Aggiungi esercizio",

        "routine.seriesList.title": "Esercizi in questa routine",
        "routine.seriesList.empty": "Nessun esercizio ancora. Aggiungine uno sopra.",

        "seriesEditor.seriesDescriptionLabel": "Descrizione dell’esercizio",
        "seriesEditor.seriesDescriptionPlaceholder": "es.: Serie di lavoro",
        "seriesEditor.restAfterSeriesLabel": "Recupero dopo l’esercizio (secondi)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "Salva esercizio",

        "seriesEditor.repGroupsTitle": "Serie",
        "seriesEditor.repGroupsEmpty": "Nessuna serie ancora. Aggiungine una sotto.",
        "seriesEditor.addRepGroupTitle": "Aggiungi serie",
        "seriesEditor.addRepGroupButton": "Aggiungi serie",

        "repGroup.lateralityLabel": "Lateralità",
        "repGroup.laterality.bilateral": "Bilaterale",
        "repGroup.laterality.unilateral": "Unilaterale",
        "repGroup.targetRepsLabel": "Ripetizioni obiettivo",
        "repGroup.targetRepsPlaceholder": "es.: 10",
        "repGroup.targetWeightSingleLabel": "Peso obiettivo",
        "repGroup.targetWeightSinglePlaceholder": "es.: 30",
        "repGroup.targetWeightTupleLabel": "Peso obiettivo (sinistra / destra)",
        "repGroup.targetWeightLeftPlaceholder": "Sinistra",
        "repGroup.targetWeightRightPlaceholder": "Destra",
        "repGroup.restAfterLabel": "Recupero dopo la serie (secondi)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "Apri",
        "common.dash": "—",
        "routines.untitled": "Routine senza titolo",
        "routines.exercisesCount.one": "{count} esercizio",
        "routines.exercisesCount.other": "{count} esercizi",
        "routines.seriesCount.one": "{count} serie",
        "routines.seriesCount.other": "{count} serie",
        "routines.count.one": "{count} routine",
        "routines.count.other": "{count} routine",
        "routines.confirmDelete": "Eliminare la routine \"{name}\"?",
        "routine.confirmDelete": "Eliminare la routine \"{name}\"?",
        "common.edit": "Modifica",
        "common.remove": "Rimuovi",
        "routine.seriesList.restAfter": "Recupero dopo: {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "Rimuovere l’esercizio n. {index}?",
        "routine.seriesList.missingExercise": "(esercizio mancante)",
        "seriesEditor.title": "Modifica esercizio n. {index} · {exercise}",
        "seriesEditor.repGroup.title": "Serie n. {index}",
        "seriesEditor.repGroup.summary": "{laterality} · ripetizioni: {reps} · peso: {weight} · recupero: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "Rimuovere la serie n. {index}?",

        "common.download": "Scarica",
        "routines.downloadHelp": "Scarica questa routine in un formato fisso che puoi utilizzare per importare le tue routine",
        "routines.upload": "Carica routine",

        "common.save": "Salva",
        "routine.edit.nameLabel": "Nome",
        "routine.edit.descLabel": "Descrizione",
        "routine.edit.namePlaceholder": "es.: Push Day A",
        "routine.edit.descPlaceholder": "Note rapide: obiettivi, intensità, focus...",

        "session.title": "Sessione di allenamento",
        "session.timer.label": "Timer",
        "session.timer.start": "Avvia",
        "session.timer.pause": "Pausa",
        "session.timer.reset": "Reimposta",
        "session.series.title": "Esercizi",
        "session.series.empty": "Questa routine non ha ancora esercizi.",
        "session.routineNotFound": "Routine non trovata.",
        "session.exercise.unknown": "Esercizio",
        "session.set": "Serie",
        "session.sets": "serie",
        "session.rest": "Recupero",
        "session.restAfterExercise": "Recupero dopo l’esercizio",
        "session.exercise.set": "serie",
        "session.exercise.sets": "serie",
        "session.currentExercise": "Esercizio corrente",
        "session.noSets": "Nessuna serie",
        "session.weight": "Peso",
        "session.reps": "Ripetizioni",
        "session.exercise": "Esercizio",
        "session.currentSet.timer": "Timer serie",
        "session.currentSet.done": "Completa serie",
        "session.allSets": "Tutte le serie",
    },

    nl: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "Minimale routinelijst. Maak en beheer trainingsplannen lokaal.",

        "common.back": "Terug",
        "common.close": "Sluiten",
        "common.cancel": "Annuleren",
        "common.create": "Aanmaken",
        "common.delete": "Verwijderen",
        "common.clearAll": "Alles wissen",

        "confirm.clearAll": "Dit verwijdert ALLE routines van dit apparaat. Doorgaan?",

        "routines.title": "Jouw routines",
        "routines.new": "+ Nieuwe routine",
        "routines.empty.prefix": "Nog geen routines. Klik op",
        "routines.empty.cta": "+ Nieuwe routine",
        "routines.empty.suffix": "om je eerste te maken.",

        "routineNew.title": "Routine maken",
        "routineNew.nameLabel": "Naam",
        "routineNew.namePlaceholder": "bijv.: Push Day A",
        "routineNew.descriptionLabel": "Beschrijving (optioneel)",
        "routineNew.descriptionPlaceholder": "Snelle notities: doelen, intensiteit, focus...",
        "routineNew.note": "Op dit apparaat opgeslagen (localStorage). Je kunt later oefeningen toevoegen in het routinescherm.",

        "routine.addSeries.title": "Oefening toevoegen",
        "routine.addSeries.exerciseLabel": "Oefening",
        "routine.addSeries.exercisePlaceholder": "Typ of kies een oefening...",
        "routine.addSeries.exerciseHelp": "Typ een nieuwe naam om de oefening automatisch aan te maken.",
        "routine.addSeries.seriesDescriptionLabel": "Beschrijving van de oefening (optioneel)",
        "routine.addSeries.seriesDescriptionPlaceholder": "bijv.: Werksets, Warming-up...",
        "routine.addSeries.button": "Oefening toevoegen",

        "routine.seriesList.title": "Oefeningen in deze routine",
        "routine.seriesList.empty": "Nog geen oefeningen. Voeg er hierboven één toe.",

        "seriesEditor.seriesDescriptionLabel": "Beschrijving van de oefening",
        "seriesEditor.seriesDescriptionPlaceholder": "bijv.: Werksets",
        "seriesEditor.restAfterSeriesLabel": "Rust na oefening (seconden)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "Oefening opslaan",

        "seriesEditor.repGroupsTitle": "Sets",
        "seriesEditor.repGroupsEmpty": "Nog geen sets. Voeg er hieronder één toe.",
        "seriesEditor.addRepGroupTitle": "Set toevoegen",
        "seriesEditor.addRepGroupButton": "Set toevoegen",

        "repGroup.lateralityLabel": "Lateralisatie",
        "repGroup.laterality.bilateral": "Bilateraal",
        "repGroup.laterality.unilateral": "Unilateraal",
        "repGroup.targetRepsLabel": "Doelreps",
        "repGroup.targetRepsPlaceholder": "bijv.: 10",
        "repGroup.targetWeightSingleLabel": "Doelgewicht",
        "repGroup.targetWeightSinglePlaceholder": "bijv.: 30",
        "repGroup.targetWeightTupleLabel": "Doelgewicht (links / rechts)",
        "repGroup.targetWeightLeftPlaceholder": "Links",
        "repGroup.targetWeightRightPlaceholder": "Rechts",
        "repGroup.restAfterLabel": "Rust na set (seconden)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "Openen",
        "common.dash": "—",
        "routines.untitled": "Routine zonder titel",
        "routines.exercisesCount.one": "{count} oefening",
        "routines.exercisesCount.other": "{count} oefeningen",
        "routines.seriesCount.one": "{count} set",
        "routines.seriesCount.other": "{count} sets",
        "routines.count.one": "{count} routine",
        "routines.count.other": "{count} routines",
        "routines.confirmDelete": "Routine \"{name}\" verwijderen?",
        "routine.confirmDelete": "Routine \"{name}\" verwijderen?",
        "common.edit": "Bewerken",
        "common.remove": "Verwijderen",
        "routine.seriesList.restAfter": "Rusttijd: {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "Oefening #{index} verwijderen?",
        "routine.seriesList.missingExercise": "(oefening ontbreekt)",
        "seriesEditor.title": "Oefening #{index} bewerken · {exercise}",
        "seriesEditor.repGroup.title": "Set #{index}",
        "seriesEditor.repGroup.summary": "{laterality} · herhalingen: {reps} · gewicht: {weight} · rust: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "Set #{index} verwijderen?",

        "common.download": "Downloaden",
        "routines.downloadHelp": "Download deze routine in een vast formaat dat je kunt gebruiken om je routines te importeren",
        "routines.upload": "Upload routine",

        "common.save": "Opslaan",
        "routine.edit.nameLabel": "Naam",
        "routine.edit.descLabel": "Beschrijving",
        "routine.edit.namePlaceholder": "bijv. Push Day A",
        "routine.edit.descPlaceholder": "Korte notities: doelen, intensiteit, focus...",

        "session.title": "Trainingssessie",
        "session.timer.label": "Timer",
        "session.timer.start": "Start",
        "session.timer.pause": "Pauze",
        "session.timer.reset": "Reset",
        "session.series.title": "Oefeningen",
        "session.series.empty": "Deze routine heeft nog geen oefeningen.",
        "session.routineNotFound": "Routine niet gevonden.",
        "session.exercise.unknown": "Oefening",
        "session.set": "Set",
        "session.sets": "sets",
        "session.rest": "Rust",
        "session.restAfterExercise": "Rust na oefening",
        "session.exercise.set": "set",
        "session.exercise.sets": "sets",
        "session.currentExercise": "Huidige oefening",
        "session.noSets": "Geen sets",
        "session.weight": "Gewicht",
        "session.reps": "Herhalingen",
        "session.exercise": "Oefening",
        "session.currentSet.timer": "Set-timer",
        "session.currentSet.done": "Set voltooien",
        "session.allSets": "Alle sets",
    },

    pl: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "Minimalna lista planów. Twórz i zarządzaj treningami lokalnie.",

        "common.back": "Wstecz",
        "common.close": "Zamknij",
        "common.cancel": "Anuluj",
        "common.create": "Utwórz",
        "common.delete": "Usuń",
        "common.clearAll": "Wyczyść wszystko",

        "confirm.clearAll": "To usunie WSZYSTKIE plany z tego urządzenia. Kontynuować?",

        "routines.title": "Twoje plany",
        "routines.new": "+ Nowy plan",
        "routines.empty.prefix": "Brak planów. Kliknij",
        "routines.empty.cta": "+ Nowy plan",
        "routines.empty.suffix": "aby utworzyć pierwszy.",

        "routineNew.title": "Utwórz plan",
        "routineNew.nameLabel": "Nazwa",
        "routineNew.namePlaceholder": "np.: Push Day A",
        "routineNew.descriptionLabel": "Opis (opcjonalnie)",
        "routineNew.descriptionPlaceholder": "Szybkie notatki: cele, intensywność, skupienie...",
        "routineNew.note": "Zapisane na tym urządzeniu (localStorage). Ćwiczenia możesz dodać później na ekranie planu.",

        "routine.addSeries.title": "Dodaj ćwiczenie",
        "routine.addSeries.exerciseLabel": "Ćwiczenie",
        "routine.addSeries.exercisePlaceholder": "Wpisz lub wybierz ćwiczenie...",
        "routine.addSeries.exerciseHelp": "Wpisz nową nazwę, aby automatycznie utworzyć ćwiczenie.",
        "routine.addSeries.seriesDescriptionLabel": "Opis ćwiczenia (opcjonalnie)",
        "routine.addSeries.seriesDescriptionPlaceholder": "np.: Serie robocze, Rozgrzewka...",
        "routine.addSeries.button": "Dodaj ćwiczenie",

        "routine.seriesList.title": "Ćwiczenia w tym planie",
        "routine.seriesList.empty": "Brak ćwiczeń. Dodaj jedno powyżej.",

        "seriesEditor.seriesDescriptionLabel": "Opis ćwiczenia",
        "seriesEditor.seriesDescriptionPlaceholder": "np.: Serie robocze",
        "seriesEditor.restAfterSeriesLabel": "Odpoczynek po ćwiczeniu (sekundy)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "Zapisz ćwiczenie",

        "seriesEditor.repGroupsTitle": "Serie",
        "seriesEditor.repGroupsEmpty": "Brak serii. Dodaj jedną poniżej.",
        "seriesEditor.addRepGroupTitle": "Dodaj serię",
        "seriesEditor.addRepGroupButton": "Dodaj serię",

        "repGroup.lateralityLabel": "Stronność",
        "repGroup.laterality.bilateral": "Obustronne",
        "repGroup.laterality.unilateral": "Jednostronne",
        "repGroup.targetRepsLabel": "Docelowe powtórzenia",
        "repGroup.targetRepsPlaceholder": "np.: 10",
        "repGroup.targetWeightSingleLabel": "Docelowy ciężar",
        "repGroup.targetWeightSinglePlaceholder": "np.: 30",
        "repGroup.targetWeightTupleLabel": "Docelowy ciężar (lewa / prawa)",
        "repGroup.targetWeightLeftPlaceholder": "Lewa",
        "repGroup.targetWeightRightPlaceholder": "Prawa",
        "repGroup.restAfterLabel": "Odpoczynek po serii (sekundy)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "Otwórz",
        "common.dash": "—",
        "routines.untitled": "Plan bez tytułu",
        "routines.exercisesCount.one": "{count} ćwiczenie",
        "routines.exercisesCount.other": "{count} ćwiczeń",
        "routines.seriesCount.one": "{count} seria",
        "routines.seriesCount.other": "{count} serii",
        "routines.count.one": "{count} plan",
        "routines.count.other": "{count} planów",
        "routines.confirmDelete": "Usunąć plan \"{name}\"?",
        "routine.confirmDelete": "Usunąć plan \"{name}\"?",
        "common.edit": "Edytuj",
        "common.remove": "Usuń",
        "routine.seriesList.restAfter": "Czas odpoczynku: {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "Usunąć ćwiczenie nr {index}?",
        "routine.seriesList.missingExercise": "(ćwiczenie nie znalezione)",
        "seriesEditor.title": "Edytuj ćwiczenie nr {index} · {exercise}",
        "seriesEditor.repGroup.title": "Seria nr {index}",
        "seriesEditor.repGroup.summary": "{laterality} · powtórzenia: {reps} · ciężar: {weight} · odpoczynek: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "Usunąć serię nr {index}?",

        "common.download": "Pobierz",
        "routines.downloadHelp": "Pobierz ten plan w stałym formacie, którego możesz użyć do importowania swoich planów",
        "routines.upload": "Prześlij plan",

        "common.save": "Zapisz",
        "routine.edit.nameLabel": "Nazwa",
        "routine.edit.descLabel": "Opis",
        "routine.edit.namePlaceholder": "np. Dzień Push A",
        "routine.edit.descPlaceholder": "Szybkie notatki: cele, intensywność, fokus...",

        "session.title": "Sesja treningowa",
        "session.timer.label": "Minutnik",
        "session.timer.start": "Start",
        "session.timer.pause": "Pauza",
        "session.timer.reset": "Resetuj",
        "session.series.title": "Ćwiczenia",
        "session.series.empty": "Ta rutyna nie zawiera jeszcze ćwiczeń.",
        "session.routineNotFound": "Nie znaleziono rutyny.",
        "session.exercise.unknown": "Ćwiczenie",
        "session.set": "Seria",
        "session.sets": "serie",
        "session.rest": "Przerwa",
        "session.restAfterExercise": "Przerwa po ćwiczeniu",
        "session.exercise.set": "seria",
        "session.exercise.sets": "serie",
        "session.currentExercise": "Bieżące ćwiczenie",
        "session.noSets": "Brak serii",
        "session.weight": "Ciężar",
        "session.reps": "Powtórzenia",
        "session.exercise": "Ćwiczenie",
        "session.currentSet.timer": "Minutnik serii",
        "session.currentSet.done": "Zakończ serię",
        "session.allSets": "Wszystkie serie",
    },

    tr: {
        "app.title": "Easy Gym Routine Tracker",
        "app.subtitle": "Minimal rutin listesi. Antrenman planlarını yerel olarak oluşturun ve yönetin.",

        "common.back": "Geri",
        "common.close": "Kapat",
        "common.cancel": "İptal",
        "common.create": "Oluştur",
        "common.delete": "Sil",
        "common.clearAll": "Hepsini temizle",

        "confirm.clearAll": "Bu, bu cihazdaki TÜM rutinleri silecek. Devam edilsin mi?",

        "routines.title": "Rutinlerin",
        "routines.new": "+ Yeni rutin",
        "routines.empty.prefix": "Henüz rutin yok. Şuna tıkla:",
        "routines.empty.cta": "+ Yeni rutin",
        "routines.empty.suffix": "ilk rutinini oluştur.",

        "routineNew.title": "Rutin oluştur",
        "routineNew.nameLabel": "Ad",
        "routineNew.namePlaceholder": "ör.: Push Day A",
        "routineNew.descriptionLabel": "Açıklama (isteğe bağlı)",
        "routineNew.descriptionPlaceholder": "Hızlı notlar: hedefler, yoğunluk, odak...",
        "routineNew.note": "Bu cihaza kaydedilir (localStorage). Daha sonra rutin ekranında egzersiz ekleyebilirsiniz.",

        "routine.addSeries.title": "Egzersiz ekle",
        "routine.addSeries.exerciseLabel": "Egzersiz",
        "routine.addSeries.exercisePlaceholder": "Bir egzersiz yazın veya seçin...",
        "routine.addSeries.exerciseHelp": "Yeni bir isim yazarak egzersizi otomatik oluşturabilirsiniz.",
        "routine.addSeries.seriesDescriptionLabel": "Egzersiz açıklaması (isteğe bağlı)",
        "routine.addSeries.seriesDescriptionPlaceholder": "ör.: Çalışma setleri, Isınma...",
        "routine.addSeries.button": "Egzersiz ekle",

        "routine.seriesList.title": "Bu rutindeki egzersizler",
        "routine.seriesList.empty": "Henüz egzersiz yok. Yukarıdan ekleyin.",

        "seriesEditor.seriesDescriptionLabel": "Egzersiz açıklaması",
        "seriesEditor.seriesDescriptionPlaceholder": "ör.: Çalışma setleri",
        "seriesEditor.restAfterSeriesLabel": "Egzersizden sonra dinlenme (saniye)",
        "seriesEditor.restAfterSeriesPlaceholder": "0",
        "seriesEditor.saveSeriesButton": "Egzersizi kaydet",

        "seriesEditor.repGroupsTitle": "Setler",
        "seriesEditor.repGroupsEmpty": "Henüz set yok. Aşağıdan ekleyin.",
        "seriesEditor.addRepGroupTitle": "Set ekle",
        "seriesEditor.addRepGroupButton": "Set ekle",

        "repGroup.lateralityLabel": "Lateralite",
        "repGroup.laterality.bilateral": "Bilateral",
        "repGroup.laterality.unilateral": "Unilateral",
        "repGroup.targetRepsLabel": "Hedef tekrar",
        "repGroup.targetRepsPlaceholder": "ör.: 10",
        "repGroup.targetWeightSingleLabel": "Hedef ağırlık",
        "repGroup.targetWeightSinglePlaceholder": "ör.: 30",
        "repGroup.targetWeightTupleLabel": "Hedef ağırlık (sol / sağ)",
        "repGroup.targetWeightLeftPlaceholder": "Sol",
        "repGroup.targetWeightRightPlaceholder": "Sağ",
        "repGroup.restAfterLabel": "Set sonrası dinlenme (saniye)",
        "repGroup.restAfterPlaceholder": "0",

        "common.open": "Aç",
        "common.dash": "—",
        "routines.untitled": "Başlıksız rutin",
        "routines.exercisesCount.one": "{count} egzersiz",
        "routines.exercisesCount.other": "{count} egzersiz",
        "routines.seriesCount.one": "{count} set",
        "routines.seriesCount.other": "{count} set",
        "routines.count.one": "{count} rutin",
        "routines.count.other": "{count} rutin",
        "routines.confirmDelete": "\"{name}\" rutini silinsin mi?",
        "routine.confirmDelete": "\"{name}\" rutini silinsin mi?",
        "common.edit": "Düzenle",
        "common.remove": "Kaldır",
        "routine.seriesList.restAfter": "Dinlenme süresi: {seconds}s",
        "routine.seriesList.confirmRemoveSeries": "#{index} egzersizi kaldırılsın mı?",
        "routine.seriesList.missingExercise": "(egzersiz bulunamadı)",
        "seriesEditor.title": "#{index} egzersizini düzenle · {exercise}",
        "seriesEditor.repGroup.title": "Set #{index}",
        "seriesEditor.repGroup.summary": "{laterality} · tekrarlar: {reps} · ağırlık: {weight} · dinlenme: {restSeconds}s",
        "seriesEditor.repGroup.confirmRemove": "Set #{index} kaldırılsın mı?",

        "common.download": "İndir",
        "routines.downloadHelp": "Rutinlerinizi içe aktarmak için kullanabileceğiniz sabit bir formatta bu rutini indirin",
        "routines.upload": "Rutin yükle",

        "common.save": "Kaydet",
        "routine.edit.nameLabel": "Ad",
        "routine.edit.descLabel": "Açıklama",
        "routine.edit.namePlaceholder": "örn. İtiş Günü A",
        "routine.edit.descPlaceholder": "Kısa notlar: hedefler, yoğunluk, odak...",

        "session.title": "Antrenman oturumu",
        "session.timer.label": "Zamanlayıcı",
        "session.timer.start": "Başlat",
        "session.timer.pause": "Duraklat",
        "session.timer.reset": "Sıfırla",
        "session.series.title": "Egzersizler",
        "session.series.empty": "Bu rutin henüz egzersiz içermiyor.",
        "session.routineNotFound": "Rutin bulunamadı.",
        "session.exercise.unknown": "Egzersiz",
        "session.set": "Set",
        "session.sets": "set",
        "session.rest": "Dinlenme",
        "session.restAfterExercise": "Egzersiz sonrası dinlenme",
        "session.exercise.set": "set",
        "session.exercise.sets": "set",
        "session.currentExercise": "Mevcut egzersiz",
        "session.noSets": "Set yok",
        "session.weight": "Ağırlık",
        "session.reps": "Tekrar",
        "session.exercise": "Egzersiz",
        "session.currentSet.timer": "Set zamanlayıcı",
        "session.currentSet.done": "Seti tamamla",
        "session.allSets": "Tüm setler",
    }
};